#!/bin/bash

# Initialise error status (to test for output differences)
ierr=0

# Test LW configuration on average columns
cp 7460_28.surflw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_lw_hadgem1_3 -R 1 9 -I -t 12 +R -v 11 -g 2 -c -C 2 -K 1 -d 1 -i 1
mv 7460_28.dflx lw_avg.dflx
mv 7460_28.hrts lw_avg.hrts
mv 7460_28.nflx lw_avg.nflx
mv 7460_28.uflx lw_avg.uflx

# Test SW
cp 7460_28.surfsw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3
mv 7460_28.hrts sw_avg.hrts
mv 7460_28.nflx sw_avg.nflx
mv 7460_28.sflx sw_avg.sflx
mv 7460_28.uflx sw_avg.uflx
mv 7460_28.vflx sw_avg.vflx
mv 7460_28.dflx sw_avg.dflx

# Test SW using delta-rescaling for the total flux but no rescaling for the direct flux 
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3 -ds 0 
mv 7460_28.hrts sw_ds0_avg.hrts
mv 7460_28.nflx sw_ds0_avg.nflx
mv 7460_28.sflx sw_ds0_avg.sflx
mv 7460_28.uflx sw_ds0_avg.uflx
mv 7460_28.vflx sw_ds0_avg.vflx
mv 7460_28.dflx sw_ds0_avg.dflx

# Test SW using delta-rescaling for the total flux but csr-phase-function rescaling for the direct flux 
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3 -ds 2 -ha 2.5 
mv 7460_28.hrts sw_ds2_avg.hrts
mv 7460_28.nflx sw_ds2_avg.nflx
mv 7460_28.sflx sw_ds2_avg.sflx
mv 7460_28.uflx sw_ds2_avg.uflx
mv 7460_28.vflx sw_ds2_avg.vflx
mv 7460_28.dflx sw_ds2_avg.dflx

# Test SW using different direct/diffuse albedos
cp 7460_28.surfsw2 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3
mv 7460_28.hrts sw2_avg.hrts
mv 7460_28.nflx sw2_avg.nflx
mv 7460_28.sflx sw2_avg.sflx
mv 7460_28.uflx sw2_avg.uflx
mv 7460_28.vflx sw2_avg.vflx
mv 7460_28.dflx sw2_avg.dflx

# Use delta-rescaling for the total flux but no rescaling for the direct flux.
# Different direct/diffuse albedos here allow the unscaled direct flux to
# affect the total flux reflected at the surface.
cp 7460_28.surfsw2 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3 -ds 0
mv 7460_28.hrts sw2_ds0_avg.hrts
mv 7460_28.nflx sw2_ds0_avg.nflx
mv 7460_28.sflx sw2_ds0_avg.sflx
mv 7460_28.uflx sw2_ds0_avg.uflx
mv 7460_28.vflx sw2_ds0_avg.vflx
mv 7460_28.dflx sw2_ds0_avg.dflx

# Test for full array of columns
cd ipa0

cp 7460_28.surflw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_lw_hadgem1_3 -R 1 9 -I -t 12 +R -v 11 -g 2 -c -C 2 -K 1 -d 1 -i 1
mv 7460_28.dflx lw.dflx
mv 7460_28.hrts lw.hrts
mv 7460_28.nflx lw.nflx
mv 7460_28.uflx lw.uflx

cp 7460_28.surfsw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3
mv 7460_28.hrts sw.hrts
mv 7460_28.nflx sw.nflx
mv 7460_28.sflx sw.sflx
mv 7460_28.uflx sw.uflx
mv 7460_28.vflx sw.vflx
mv 7460_28.dflx sw.dflx

diff -q ref_lw.dflx lw.dflx || ierr=1
diff -q ref_lw.hrts lw.hrts || ierr=1
diff -q ref_lw.nflx lw.nflx || ierr=1
diff -q ref_lw.uflx lw.uflx || ierr=1
diff -q ref_sw.hrts sw.hrts || ierr=1
diff -q ref_sw.nflx sw.nflx || ierr=1
diff -q ref_sw.sflx sw.sflx || ierr=1
diff -q ref_sw.uflx sw.uflx || ierr=1
diff -q ref_sw.vflx sw.vflx || ierr=1
diff -q ref_sw.dflx sw.dflx || ierr=1
resrm lw
resrm sw

cd ..
rm cdl_sw_avg* 2> /dev/null
Ccdf2cdl -a sw_avg > /dev/null
rm cdl_lw_avg* 2> /dev/null
Ccdf2cdl -a lw_avg > /dev/null
diff -q ref_lw_avg.dflx cdl_lw_avg.dflx || ierr=1
diff -q ref_lw_avg.hrts cdl_lw_avg.hrts || ierr=1
diff -q ref_lw_avg.nflx cdl_lw_avg.nflx || ierr=1
diff -q ref_lw_avg.uflx cdl_lw_avg.uflx || ierr=1
diff -q ref_sw_avg.hrts cdl_sw_avg.hrts || ierr=1
diff -q ref_sw_avg.nflx cdl_sw_avg.nflx || ierr=1
diff -q ref_sw_avg.sflx cdl_sw_avg.sflx || ierr=1
diff -q ref_sw_avg.uflx cdl_sw_avg.uflx || ierr=1
diff -q ref_sw_avg.vflx cdl_sw_avg.vflx || ierr=1
diff -q ref_sw_avg.dflx cdl_sw_avg.dflx || ierr=1
resrm lw_avg
resrm sw_avg

rm cdl_sw_ds0_avg* 2> /dev/null
Ccdf2cdl -a sw_ds0_avg  > /dev/null
diff -q ref_sw_ds0_avg.hrts cdl_sw_ds0_avg.hrts || ierr=1
diff -q ref_sw_ds0_avg.nflx cdl_sw_ds0_avg.nflx || ierr=1
diff -q ref_sw_ds0_avg.sflx cdl_sw_ds0_avg.sflx || ierr=1
diff -q ref_sw_ds0_avg.uflx cdl_sw_ds0_avg.uflx || ierr=1
diff -q ref_sw_ds0_avg.vflx cdl_sw_ds0_avg.vflx || ierr=1
diff -q ref_sw_ds0_avg.dflx cdl_sw_ds0_avg.dflx || ierr=1
resrm sw_ds0_avg

rm cdl_sw_ds2_avg* 2> /dev/null
Ccdf2cdl -a sw_ds2_avg  > /dev/null
diff -q ref_sw_ds2_avg.hrts cdl_sw_ds2_avg.hrts || ierr=1
diff -q ref_sw_ds2_avg.nflx cdl_sw_ds2_avg.nflx || ierr=1
diff -q ref_sw_ds2_avg.sflx cdl_sw_ds2_avg.sflx || ierr=1
diff -q ref_sw_ds2_avg.uflx cdl_sw_ds2_avg.uflx || ierr=1
diff -q ref_sw_ds2_avg.vflx cdl_sw_ds2_avg.vflx || ierr=1
diff -q ref_sw_ds2_avg.dflx cdl_sw_ds2_avg.dflx || ierr=1
resrm sw_ds2_avg

rm cdl_sw2_avg* 2> /dev/null
Ccdf2cdl -a sw2_avg > /dev/null
diff -q ref_sw2.hrts cdl_sw2_avg.hrts || ierr=1
diff -q ref_sw2.nflx cdl_sw2_avg.nflx || ierr=1
diff -q ref_sw2.sflx cdl_sw2_avg.sflx || ierr=1
diff -q ref_sw2.uflx cdl_sw2_avg.uflx || ierr=1
diff -q ref_sw2.vflx cdl_sw2_avg.vflx || ierr=1
diff -q ref_sw2.dflx cdl_sw2_avg.dflx || ierr=1
resrm sw2_avg

rm cdl_sw2_ds0_avg* 2> /dev/null
Ccdf2cdl -a sw2_ds0_avg > /dev/null
diff -q ref_sw2_ds0.hrts cdl_sw2_ds0_avg.hrts || ierr=1
diff -q ref_sw2_ds0.nflx cdl_sw2_ds0_avg.nflx || ierr=1
diff -q ref_sw2_ds0.sflx cdl_sw2_ds0_avg.sflx || ierr=1
diff -q ref_sw2_ds0.uflx cdl_sw2_ds0_avg.uflx || ierr=1
diff -q ref_sw2_ds0.vflx cdl_sw2_ds0_avg.vflx || ierr=1
diff -q ref_sw2_ds0.dflx cdl_sw2_ds0_avg.dflx || ierr=1
resrm sw2_ds0_avg

if [ $ierr -gt 0 ] ; then
  exit 1
else
  resrm cdl_lw_avg
  resrm cdl_sw_avg
  resrm cdl_sw2_avg
  resrm cdl_sw2_ds0_avg
  resrm cdl_sw_ds0_avg
  resrm cdl_sw_ds2_avg
  echo OK
  exit 0
fi
