#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

# Create skeleton spectral file:
# 20 bands
# 5 gases: CH4 (6), H2 (23), He (24), C2H2 (34), C2H6 (46)
# 2 CIA: H2-H2, H2-He
# No aerosols
# Bands specified in microns (u)
prep_spec << EOF > ${skelfile}_log
${skelfile}
20
5
6
23
24
34
46
2
23 23
23 24
0
r
u 3.3 1003.3 50
0*20
0*20
n
-1
EOF

fi
exit 0
