#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

# Create skeleton spectral file:
# 500 bands
# 5 gases: C2H2, C2H6, CH4, H2, He
# 2 CIA: H2-H2, H2-He
# No aerosols
# Bands specified in microns (u)
prep_spec << EOF > ${skelfile}_log
${skelfile}
500
5
6
23
24
34
46
2
23 23
23 24
0
r
u 3.3 1003.3 2.0
0*500
0*500
n
-1
EOF

fi
exit 0

