#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

. ./env_uranus
nbands=${NBANDS_HR_SW}

# Create skeleton spectral file:
# 293 bands from 0.3 to 15 microns
# 5 gases: CH4 (6), H2 (23), He (24), C2H2 (34), C2H6 (46)
# 2 CIA: H2-H2, H2-He
# No aerosols
# Bands specified in microns (u)
prep_spec << EOF > ${skelfile}_log
${skelfile}
${nbands}
5
6
23
24
34
46
2
23 23
23 24
0
r
u 0.3 0.9 0.005
u 0.9 1.2 0.015
u 1.2 2.4 0.02
u 2.4 3.6 0.05
u 3.6 6.0 0.1
u 6.0 15.0 0.2
0*${nbands}
0*${nbands}
n
-1
EOF

fi
exit 0
