#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

. ./env_uranus
nbands=${NBANDS_HR_LW}

# Create skeleton spectral file:
# 319 bands from 3.125 to 1000 microns
# 5 gases: CH4 (6), H2 (23), He (24), C2H2 (34), C2H6 (46)
# 2 CIA: H2-H2, H2-He
# No aerosols
# Bands specified in wavenumbers (c)
prep_spec << EOF > ${skelfile}_log
${skelfile}
${nbands}
5
6
23
24
34
46
2
23 23
23 24
0
r
c 3200 10 -10
0*${nbands}
0*${nbands}
n
-1
EOF

fi
exit 0
